#define LINE_FOLLOWER_PIN 48
#define WHEEL_ENCODER_1_PIN 50
#define WHEEL_ENCODER_2_PIN 51

#define ULTRASONIC_ECHO_PIN A7
#define ULTRASONIC_TRIG_PIN 2

#define M1_PWM_PIN 3
#define M1_DIR_PIN 4

#define M2_PWM_PIN 6
#define M2_DIR_PIN 5

#define M3_PWM_PIN 7
#define M3_DIR_PIN 8

#define M4_PWM_PIN 9
#define M4_DIR_PIN 10