#define LINE_FOLLOWER_1_DIGITAL_PIN 48
#define LINE_FOLLOWER_1_ANALOG_PIN A0

#define LINE_FOLLOWER_2_DIGITAL_PIN 23
#define LINE_FOLLOWER_2_ANALOG_PIN A1

#define WHEEL_ENCODER_1_PIN 50
#define WHEEL_ENCODER_2_PIN 51

#define TOF_RIGHT_XSHUT_PIN 52
#define TOF_LEFT_XSHUT_PIN 40

#define IR_PIN 41

#define M1_PWM_PIN 3
#define M1_DIR_PIN 4

#define M2_PWM_PIN 6
#define M2_DIR_PIN 5

#define M3_PWM_PIN 7
#define M3_DIR_PIN 8

#define M4_PWM_PIN 9
#define M4_DIR_PIN 10
