#include <math.h>
#define BLACK_ANALOG_READ_THRESHOLD 900

#define MIN_DISTANCE_TO_OBJECT 30 //in cm
#define NUM_CONSECUTIVE_DETECTIONS_ULTRASONIC 35
#define NUM_CONSECUTIVE_DETECTIONS_LINE_SENSOR 10

#define WHEEL_DIAMETER 15
#define DISTANCE_BETWEEN_WHEELS 15
#define WIDTH 22.6
#define ENCODER_TEETH 10
#define EXPERIMENTAL_PULSE_OFFSET 0

#define WHEEL_CIRCUMFERENCE WHEEL_DIAMETER*PI
#define X_CONSTANT 1.48
#define X0 X_CONSTANT*DISTANCE_BETWEEN_WHEELS/2
#define DEGREES_TURN 90
#define DEGREES_IN_RADS DEGREES_TURN * 180/PI
#define NUMBER_OF_FULL_REVOLUTIONS_FOR_90 (DEGREES_IN_RADS * X0)/WHEEL_CIRCUMFERENCE
#define NUMBER_OF_FULL_REVOLUTIONS_FOR_WIDTH WIDTH/WHEEL_CIRCUMFERENCE

#define NUMBER_OF_ENCODER_PULSES_FOR_90 ENCODER_TEETH * NUMBER_OF_FULL_REVOLUTIONS_FOR_90 - EXPERIMENTAL_PULSE_OFFSET
#define NUMBER_OF_ENCODER_PULSES_FOR_WIDTH ENCODER_TEETH * NUMBER_OF_FULL_REVOLUTIONS_FOR_WIDTH